/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-108331-g257eea3db4-20220924"
#endif /* AVUTIL_FFVERSION_H */
